site_name: BIBBOX

pages:
    - Introduction: index.md
    - Installation from image: installation-image.md
    - Installation with vagrant: installation-vagrant.md
    - Installation from source: installation-source.md
    - Install Apps: admin-documentation.md
    - Create Apps: app-creators-manual.md
    - Intstall Apps:
        - OpenSpecimen: apptutorials/openspecimen/openspecimen.md
        - Phenotips: apptutorials/phenotips/phenotips.md
    - Under the hood: technical.md

theme: readthedocs