site_name: BIBBOX

pages:
    - V4 - Beta: 
        - Set-up/Get started: index.md
        - Install V4 (Linux): installation_v4_linux.md
        - V4 - Create Apps: app-creators-manual_v4.md
    - V3 - Old Documentation:
        - Introduction: v3_introduction.md
        - Installation from image: installation-image.md
        - Installation from source: installation-source.md
        - Install Apps: admin-documentation.md
        - Create Apps: app-creators-manual.md
        - Intstall Apps:
            - OpenSpecimen: apptutorials/openspecimen/openspecimen.md
            - Phenotips: apptutorials/phenotips/phenotips.md
            - Molgenis: apptutorials/molgenis/molgenis.md
        - Under the hood: technical.md

theme: readthedocs
