site_name: BIBBOX

pages:
    - V4 - Beta: 
        - Documentation: index.md
        - V4 - Create Apps: app-creators-manual_v4.md
    - V3 - Old Documentation:
        - Introduction: index.md
        - Installation from image: installation-image.md
        - Installation from source: installation-source.md
        - Install Apps: admin-documentation.md
        - Create Apps: app-creators-manual.md
        - Intstall Apps:
            - OpenSpecimen: apptutorials/openspecimen/openspecimen.md
            - Phenotips: apptutorials/phenotips/phenotips.md
            - Molgenis: apptutorials/molgenis/molgenis.md
        - Under the hood: technical.md

theme: readthedocs
