site_name: eB3Kit

pages:
    - Introduction: introduction.md
    - Installation: installation.md
    - Ethical Framework: ethics.md
    - Install Applications: admin-documentation.md
    - Manage Applicatoins: pi-curators-documentation.md
    - Use Applicatons:
        - Bika: apptutorials/bika.md
        - Phenotips: apptutorials/phenotips.md
