site_name: BIBBOX

pages:
    - Introduction: index.md
    - Installation: installation.md
    - Ethical Framework: ethics.md
    - Install Apps: admin-documentation.md
    - Create Apps: app-creators-manual.md
    - Manage Apps: pi-curators-documentation.md
    - Integrate Apps:
        - Bika: apptutorials/bika.md
        - Phenotips: apptutorials/phenotips.md
    - Behind the Scenes: technical.md

theme: readthedocs