site_name: BIBBOX

nav:
    - Introduction: index.md
    - Install guide: installation_v4_bibbox_linux.md
    - User guide: user-guide.md
    - Developer guide: developer-guide.md
    - Citation: citation.md
    - License: license.md


theme: 
    name: readthedocs


